# -*- coding: utf-8 -*-
"""CNN from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8LSgkFrR-VF9Gi-VsBkYzQq9gUDo3bW

This is my sophomore summer vacation project, Convolutional Neural Network with python and only numpy.
"""

import numpy as np
def im2col(X, filter_h, filter_w, stride=1, pad=0):
    '''(N,C,H,W) 텐서 X를 (N*out_h*out_w, C, filter_h, filter_w) 크기의 자취텐서로 변환 후
    (N*out_h*out_w, C*filter_h*filter_w)의 행렬로 변환'''

    N, C, H, W=X.shape
    out_h, out_w = 1 + (H + 2 * pad - filter_h) // stride, 1 + (W + 2 * pad - filter_w) // stride
    img = np.pad(X, [(0,0), (0,0), (pad, pad), (pad, pad)], mode = 'constant')
    cols=np.zeros((N, C, out_h, out_w, filter_h, filter_w))

    for i in range(filter_h):
        max_i = i + out_h * stride
        for j in range(filter_w):
            max_j = j + out_w * stride
            cols[:,:,:,:,i, j] = img[:,:,i:max_i:stride, j:max_j:stride]

    cols = cols.transpose(0,2,3,1,4,5).reshape((N * out_h * out_w, C * filter_h * filter_w))

    return cols

def col2im(cols, x_shape, filter_h, filter_w, stride=1, pad=0):
    '''im2col의 역연산: (N*out_h*out_w, C*filter_h*filter_w) 행렬을 (N, C, H, W) 텐서로 복원'''

    N, C, H, W = x_shape
    out_h, out_w = 1 + (H + 2 * pad - filter_h) // stride, 1 + (W + 2 * pad - filter_w) // stride

    # transpose 전 차원으로 reshape
    cols = cols.reshape(N, out_h, out_w, C, filter_h, filter_w).transpose(0, 3, 1, 2, 4, 5)

    x = np.zeros((N, C, H+2*pad, W+2*pad))
    for i in range(filter_h):
        max_i = i + out_h * stride
        for j in range(filter_w):
            max_j = j + out_w * stride
            x[:, :, i:max_i:stride, j:max_j:stride] += cols[:, :, :, :, i, j]

    if pad==0:
        return x
    else:
        return x[:, :, pad:H + pad, pad:W + pad]

class Conv2D:
    '''(inc=C) (inc, h, w)의 3차원 필터 텐서를 X (N, C, H+2pad, W+2pad)에
    stride만큼 슬라이딩하면서 feature 추출 및 gradient 계산'''

    def __init__(self, outc, inc, h, w, stride=1, pad=0):
        self.outc = outc
        self.inc = inc
        self.h = h
        self.w = w
        self.stride=stride
        self.pad=pad
        self.W = np.random.randn(outc, inc, h, w) * np.sqrt(2/(inc*h*w))
        self.b = np.zeros(outc)
        self.X = None
        self.X_col = None
        self.W_row = None
        self.dW = None
        self.db = None

    def Forward(self, X):
        self.X = X
        N, C, H, W = X.shape
        out_h = 1 + (H + 2*self.pad - self.h) // self.stride
        out_w = 1 + (W + 2*self.pad - self.w) // self.stride

        # im2col 변환 (N * out_h * out_w, inc * h * w)
        self.X_col = im2col(X, self.h, self.w, self.stride, self.pad)

        # 가중치 평탄화 (outc, inc * h * w)
        self.W_row = self.W.reshape(self.outc, -1)

        # 행렬 곱 (X_col @ W_row.T)
        out = np.dot(self.X_col, self.W_row.T) + self.b

        # 출력 형태 복원 (N, outc, outh, outw)
        out = out.reshape(N, out_h, out_w, self.outc).transpose(0, 3, 1, 2)
        return out

    def Backward(self, dout):
        # dout shape: (N, outc, outh, outw)
        N, C, H, W = self.X.shape

        # dout 차원 재정렬 (N * outh * outw, outc)
        dout_reshaped = dout.transpose(0, 2, 3, 1).reshape(-1, self.outc)

        # db (outc,)
        self.db = np.sum(dout_reshaped, axis=0)

        # dW (outc, inc * H * W) -> reshape (outc, inc, H, W)
        self.dW = np.dot(dout_reshaped.T, self.X_col)
        self.dW = self.dW.reshape(self.outc, self.inc, self.h, self.w)

        # dX_col (N * outh * outw, inc * H * W)
        dX_col = np.dot(dout_reshaped, self.W_row)

        # col2im (N, inc, H, W)
        dX = col2im(dX_col, self.X.shape, self.h, self.w, self.stride, self.pad)

        return dX

class ReLU:
    '''비선형 함수 ReLU (max(0, X))'''

    def __init__(self):
        self.mask = None
        self.X = None
        self.dX = None

    def Forward(self, X):
        self.mask = (X <= 0)
        self.X = X.copy()
        self.X[self.mask] = 0
        return self.X

    def Backward(self, dout):
        self.dX = dout.copy()
        self.dX[self.mask] = 0
        return self.dX

class MaxPool2D:
    ''' (C, pool_h, pool_w)의 3차원 필터 텐서를 X (N, C, H+2pad, W+2pad)에
        stride만큼 슬라이딩하면서 max value추출, index 추출 및 index 위치에만 gradient 계산'''

    def __init__(self, pool_h=2, pool_w=2, stride=2, pad=0):
        self.pool_h = pool_h
        self.pool_w = pool_w
        self.stride = stride
        self.pad = pad

        self.X = None
        self.arg_max = None

    def Forward(self, X):
        self.X = X
        N, C, H, W = X.shape
        out_h = 1 + (H + 2*self.pad - self.pool_h) // self.stride
        out_w = 1 + (W + 2*self.pad - self.pool_w) // self.stride

        # im2col 변환 (N * out_h * out_w, C * pool_h * pool_w)
        col = im2col(X, self.pool_h, self.pool_w, self.stride, self.pad)
        # reshape
        col = col.reshape(-1, self.pool_h * self.pool_w)

        # 각 영역에서의 최댓값 및 최댓값 인덱스 구하기
        arg_max = np.argmax(col, axis=1)
        self.arg_max = arg_max
        out = np.max(col, axis=1)

        # 출력 형태 변형
        out = out.reshape(N, out_h, out_w, C).transpose(0, 3, 1, 2)
        return out

    def Backward(self, dout):
        dout = dout.transpose(0, 2, 3, 1)
        N, H, W, C = dout.shape
        pool_size = self.pool_h * self.pool_w
        dmax = np.zeros((dout.size, pool_size))

        # 최댓값을 출력했던 위치에만 dout 할당
        dmax[np.arange(self.arg_max.size), self.arg_max.flatten()] = dout.flatten()
        dmax = dmax.reshape(N * H * W, -1)

        # col2im (N, C, H, W)
        dX = col2im(dmax, self.X.shape, self.pool_h, self.pool_w, self.stride, self.pad)

        return dX

class FC:
    def __init__(self, in_features, out_features):
        # in_features: Flatten size(C * H * W), out_features: the number of category
        self.W = np.random.randn(in_features, out_features) * np.sqrt(2.0 / in_features)
        self.b = np.zeros(out_features)
        self.X = None
        self.original_x_shape = None
        self.dW = None
        self.db = None

    def Forward(self, X):
        self.original_x_shape = X.shape
        self.X = X.reshape(X.shape[0], -1)

        out = np.dot(self.X, self.W) + self.b
        return out

    def Backward(self, dout):
        self.dW = np.dot(self.X.T, dout)
        self.db = np.sum(dout, axis=0)

        dX = np.dot(dout, self.W.T)
        # 입력받았을 때의 원본 텐서 모양으로 복원하여 반환
        return dX.reshape(*self.original_x_shape)

class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None  # softmax의 출력
        self.t = None  # 정답 레이블 (one-hot Vector 혹은 라벨 인덱스)

    def Forward(self, X, t):
        self.t = t
        exp_x = np.exp(X - np.max(X, axis = 1, keepdims = True))
        self.y = exp_x / np.sum(exp_x, axis = 1, keepdims = True)
        N = X.shape[0]

        if self.t.ndim == 1:
            self.loss = -np.sum(np.log(self.y[np.arange(N), self.t] + 1e-7)) / N
        else:
            self.loss = -np.sum(self.t * np.log(self.y + 1e-7)) / N

        return self.loss

    def Backward(self, dout=1):
        N = self.t.shape[0]

        if self.t.ndim == 1:
            dX = self.y.copy()
            dX[np.arange(N), self.t] -= 1
            dX = (dX / N) * dout
        else:
            dX = ((self.y - self.t) / N) * dout

        return dX

class CNN:
    def __init__(self, out_channel=16, in_channel=3, height=3, width=3, stride=1, pad=0 ,lr=0.01):
        self.outc = out_channel
        self.inc = in_channel
        self.h = height
        self.w = width
        self.stride= stride
        self.pad = pad
        self.lr = lr
        self.layers = [
            Conv2D(self.outc, self.inc, self.h, self.w, self.stride, self.pad),
            ReLU()
        ]
        self.last_layer = SoftmaxWithLoss()
        self.is_built = False

    def _build_network(self, x, t):
        """첫 Forward/Learning 시점에 입력 x와 정답 t를 분석하여 레이어를 1회 완공"""
        N, C, H, W = x.shape

        if H != W:
            raise ValueError('이미지의 높이와 너비가 맞지 않습니다.')

        if t.ndim == 1:
            num_classes = np.max(t) + 1
        else:
            num_classes = t.shape[1]

        out_h = 1 + (H + 2 * self.pad - self.h) // self.stride
        k = out_h

        while (k % 2 == 0) and (k > 10):
            if (k % 4 != 0) and (k > 20):
                self.layers.append(MaxPool2D(pad=1))
                k = (k // 2) + 1
            else:
                self.layers.append(MaxPool2D())
                k = k // 2
            self.layers.append(ReLU())

        flatten_size = self.outc * k * k
        self.layers.append(FC(flatten_size, num_classes))
        self.is_built = True

    def predict(self, x):
        if not self.is_built:
            raise ValueError("모델이 아직 초기화되지 않았습니다. learning(x, t)을 먼저 실행하세요.")

        for layer in self.layers:
            x = layer.Forward(x)
        return x

    def loss(self, x, t):
        y = self.predict(x)
        return self.last_layer.Forward(y, t)

    def learning(self, x, t):
        # 첫 번째 배치 학습 시 네트워크를 동적으로 1회 구축
        if not self.is_built:
            self._build_network(x, t)

        loss_val = self.loss(x, t)

        dout = self.last_layer.Backward()
        for layer in reversed(self.layers):
            dout = layer.Backward(dout)
            if hasattr(layer, 'b'):
                layer.W -= self.lr * layer.dW
                layer.b -= self.lr * layer.db

        return loss_val

    def probability(self, x):
        y=self.predict(x)
        exp_y = np.exp(y - np.max(y, axis = 1, keepdims = True))
        prob = exp_y / np.sum(exp_y, axis = 1, keepdims = True)
        return prob

#MNIST 테스트
from sklearn.datasets import fetch_openml

# 1. OpenML에서 MNIST 데이터 로드 (784 차원 -> 28x28 이미지)
mnist = fetch_openml('mnist_784', version=1, as_frame=False)

X = mnist.data.astype(np.float32)  # (70000, 784)
t = mnist.target.astype(np.int32)   # (70000,)

# 2. 전처리: 0.0 ~ 1.0 정규화 및 (N, C, H, W) 텐서 변환
X /= 255.0
X = X.reshape(-1, 1, 28, 28)

# 학습용(60,000장)과 테스트용(10,000장) 분리
x_train, x_test = X[:60000], X[60000:]
t_train, t_test = t[:60000], t[60000:]

# 3. 모델 객체 생성
# (28x28 흑백 이미지가 들어오면 첫 배치 때 FC층과 MaxPool층이 동적으로 빌드됨)
cnn = CNN(out_channel=16, in_channel=1, height=3, width=3, stride=1, pad=1, lr=0.01)

# 4. 미니배치 학습 설정
iters_num = 1000      # 총 반복 횟수
train_size = x_train.shape[0]
batch_size = 100      # 미니배치 크기

print("\n2. 학습 시작!")
for i in range(iters_num):
    # 무작위 미니배치 추출
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]

    # 학습 및 손실 계산
    loss_val = cnn.learning(x_batch, t_batch)

    if (i + 1) % 100 == 0:
        print(f"Iteration {i+1:4d} / {iters_num} | Loss: {loss_val:.4f}")

# 5. 테스트 데이터로 정확도 검증
test_preds = cnn.predict(x_test[:1000])  # 시간 관계상 1,000개만 샘플 테스트
predicted_labels = np.argmax(test_preds, axis=1)
accuracy = np.mean(predicted_labels == t_test[:1000]) * 100

print(f"\n3. 테스트 데이터 샘플 정확도: {accuracy:.2f}%")